### ISSUE TITLE
关于双列表在一个列表滚动问题

### ISSUE THREAD

**Issue by andZhangjiong** [CoderLineChan/LCPageView#2]
最近一直在研究饿了吗商家详情界面，发现很难找到合适的demo，scrollView切换到tableVIew有卡顿的效果，不知道你有没有时间写个demo放在github上面给你关于饿了吗ios关于多列表手势切换问题的一篇文章http://mobilists.eleme.io/2016/03/15/用UIKit-Dynamics模仿UIScrollView/

**Comment by CoderLineChan** [comment]
好的， 我有时间试试看！
