### ISSUE TITLE
下载下来的工程不可用啊，请楼楼改下，谢谢

### ISSUE THREAD

**Issue by jaylees** [CoderLineChan/LCPageView#3]

**Comment by CoderLineChan** [comment]
好的！

**Comment by CoderLineChan** [comment]
已经弄好了， 可以去下载最新的工程

**Comment by jaylees** [comment]
tanks




| |
ahlsjie
邮箱：ahlsjie@126.com
|

Signature is customized by Netease Mail Master

在2018年09月11日 10:59，陈陈陈 写道：

Closed #3.
